### ISSUE TITLE
(Segmentation fault) ProcessDelayedDamages may have caused my worldserver process to crash

### ISSUE THREAD

**Issue by WildBlizzard** [azerothcore/azerothcore-wotlk#16160]
### Current Behaviour

The recent commit seems to have caused a service crash.

Program terminated with signal 11, Segmentation fault.
#0  0x0000556d48e636c6 in Unit::DealDamage(Unit*, Unit*, unsigned int, CleanDamage const*, DamageEffectType, SpellSchoolMask, SpellInfo const*, bool, bool, Spell const*, bool) ()

#0  0x0000556d48e636c6 in Unit::DealDamage(Unit*, Unit*, unsigned int, CleanDamage const*, DamageEffectType, SpellSchoolMask, SpellInfo const*, bool, bool, Spell const*, bool) ()
#1  0x0000556d49260b9e in World::ProcessDelayedDamages() ()
#2  0x0000556d4928a1ab in World::Update(unsigned int) ()
#3  0x0000556d48311d14 in WorldUpdateLoop() ()
#4  0x0000556d482cad9e in main ()

### Expected Blizzlike Behaviour

Not crash

### Steps to reproduce the problem

Unkown

### AC rev. hash/commit

590dcca82b9c6e5d5f49fb5f954b084a88070f84

### Operating system

CentOS7.9

**Comment by WildBlizzard** [comment]
Seems relate to #14199

**Comment by WildBlizzard** [comment]
Sad, stll crash...
We were playing instance when crashed .
![image](https://user-images.githubusercontent.com/32586354/235951600-f4abaf77-d23d-4cac-8c5d-1e109b9ea6ff.png)
