### ISSUE TITLE
Install with Docker not working on Windows 11

### ISSUE THREAD

**Issue by byte-bandit** [azerothcore/azerothcore-wotlk#17063]
### Current Behaviour

Following https://www.azerothcore.org/wiki/install-with-docker to the line:

```bash
git clone https://github.com/azerothcore/azerothcore-wotlk.git
cd azerothcore-wotlk
./acore.sh docker build
./acore.sh docker client-data
./acore.sh docker start:app
```

This currently results in this:
```bash
$ ./acore.sh docker start:app
NOTICE: file </d/git/azerothcore-wotlk/conf/config.sh> not found, we use default configuration only.
Deno version check:
Version 1.26.0 is already installed
>>>>> Running: docker compose --profile app up
[+] Running 5/3
 ✔ Network azerothcore-wotlk_ac-network          Created                                                           0.6s
 ✔ Container azerothcore-wotlk-ac-database-1     Created                                                           0.0s
 ✔ Container azerothcore-wotlk-ac-db-import-1    Created                                                           0.0s
 ✔ Container azerothcore-wotlk-ac-authserver-1   Created                                                           0.0s
 ✔ Container azerothcore-wotlk-ac-worldserver-1  Created                                                           0.0s
Attaching to azerothcore-wotlk-ac-authserver-1, azerothcore-wotlk-ac-database-1, azerothcore-wotlk-ac-db-import-1, azerothcore-wotlk-ac-worldserver-1
azerothcore-wotlk-ac-database-1     | 2023-08-23 08:59:00+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.34-1.el8 started.
azerothcore-wotlk-ac-database-1     | 2023-08-23 08:59:01+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'azerothcore-wotlk-ac-database-1     | 2023-08-23 08:59:01+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.34-1.el8 started.
azerothcore-wotlk-ac-database-1     | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
azerothcore-wotlk-ac-database-1     | 2023-08-23T08:59:01.326461Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
azerothcore-wotlk-ac-database-1     | 2023-08-23T08:59:01.327350Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.34) starting as process 1
azerothcore-wotlk-ac-database-1     | 2023-08-23T08:59:01.342472Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
azerothcore-wotlk-ac-database-1     | 2023-08-23T08:59:01.455246Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
azerothcore-wotlk-ac-database-1     | 2023-08-23T08:59:01.596723Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
azerothcore-wotlk-ac-database-1     | 2023-08-23T08:59:01.596759Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
azerothcore-wotlk-ac-database-1     | 2023-08-23T08:59:01.603795Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
azerothcore-wotlk-ac-database-1     | 2023-08-23T08:59:01.616760Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
azerothcore-wotlk-ac-database-1     | 2023-08-23T08:59:01.616826Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.34'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
azerothcore-wotlk-ac-db-import-1 exited with code 1
service "ac-db-import" didn't complete successfully: exit 1
error: Uncaught (in promise) Error: Failed with error: 1, however,
          it's not related to this Deno script directly. An error occurred within
          the script called by the command itself
          throw new Error(`Failed with error: ${status.code}, however,
                ^
    at Command.<anonymous> (file:///D:/git/azerothcore-wotlk/apps/docker/docker-cmd.ts:268:17)
    at async Promise.all (index 0)
    at async main (file:///D:/git/azerothcore-wotlk/apps/docker/docker-cmd.ts:324:7)
```

`docker container logs azerothcore-wotlk-ac-db-import-1` does not return aany logs.

### Expected Blizzlike Behaviour

Database migration runner should execute without an error.

### Steps to reproduce the problem

```bash
git clone https://github.com/azerothcore/azerothcore-wotlk.git
cd azerothcore-wotlk
./acore.sh docker build
./acore.sh docker client-data
./acore.sh docker start:app
```

### AC rev. hash/commit

4c287e2873c3464a64baafc8c93a47521bccfbc9

### Operating system

Windows 11 x64, MINWG64

### Custom changes or Modules

None

**Comment by michaeldelago** [comment]
@byte-bandit 

From a high level, this is caused by 2 things

1. The `dbimport` doesn't issue an error or warning if there's a missing config file
2. I removed the code that copies the file at `env/dist/etc/dbimport.conf.dist` to `env/dist/etc/dbimport.conf` (this also applies to `worldserver.conf` and `authserver.conf`

1 is a bug, 2 is a regression and both should be fixed.

**Comment by byte-bandit** [comment]
@michaeldelago 

That seems to be it. After manually copying the files you mentioned, DB migration worked as expected. 

I believe [this ](https://github.com/azerothcore/azerothcore-wotlk/commit/f241a6e352176dc55b0682f00c3460256abc010a)is the change that removed the copying logic?

I don't know enough about your motivation to remove this here. If you give me some context, I'm happy to open a PR with a fix for this.

**Comment by byte-bandit** [comment]
This was fixed with https://github.com/azerothcore/azerothcore-wotlk/pull/17066
