### ISSUE TITLE
Hackers attacks - worldserver crashed

### ISSUE THREAD

**Issue by zqgmzq** [azerothcore/azerothcore-wotlk#2043]
###

##### SMALL DESCRIPTION:

I add gdb log
its repeated >30 times

##### STEPS TO REPRODUCE THE PROBLEM:

1. Wait for attack
2. Crash
3. Done

##### EXTRA NOTES:

Wed Jul 3 08:44:01 MSK 2019
 ===================
```
#0  0x0000000000b816d7 in Trinity::ObjectUpdater::Visit<Creature> (this=<optimized out>, m=...) at /home/azerothcore/src/server/game/Grids/Notifiers/GridNotifiers.cpp:324
#1  0x0000000000bf0109 in VisitorHelper<Trinity::ObjectUpdater, Creature> (v=..., c=...) at /home/azerothcore/src/common/Dynamic/TypeContainerVisitor.h:48
#2  VisitorHelper<Trinity::ObjectUpdater, Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > (v=..., c=...) at /home/azerothcore/src/common/Dynamic/TypeContainerVisitor.h:54
#3  VisitorHelper<Trinity::ObjectUpdater, GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > (v=..., c=...) at /home/azerothcore/src/common/Dynamic/TypeContainerVisitor.h:55
#4  VisitorHelper<Trinity::ObjectUpdater, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > (v=..., c=...) at /home/azerothcore/src/common/Dynamic/TypeContainerVisitor.h:76
#5  TypeContainerVisitor<Trinity::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >::Visit (this=<optimized out>, c=...) at /home/azerothcore/src/common/Dynamic/TypeContainerVisitor.h:87
#6  Grid<Player, TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > >, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > >::Visit<Trinity::ObjectUpdater> (this=<optimized out>, visitor=...) at /home/azerothcore/src/server/game/Grids/Grid.h:79
#7  NGrid<8u, Player, TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > >, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > >::VisitGrid<Trinity::ObjectUpdater, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > (x=<optimized out>, y=<optimized out>, this=<optimized out>, visitor=...) at /home/azerothcore/src/server/game/Grids/NGrid.h:93
#8  Map::Visit<Trinity::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > > (this=<optimized out>, cell=..., visitor=...) at /home/azerothcore/src/server/game/Maps/Map.h:717
#9  Map::VisitNearbyCellsOf (this=<optimized out>, obj=<optimized out>, gridVisitor=..., worldVisitor=...) at /home/azerothcore/src/server/game/Maps/Map.cpp:650
#10 0x0000000000bf06df in Map::Update (this=<optimized out>, t_diff=<optimized out>, s_diff=<optimized out>) at /home/azerothcore/src/server/game/Maps/Map.cpp:747
#11 0x0000000000bfd67e in MapUpdateRequest::call (this=0x7fff75852100) at /home/azerothcore/src/server/game/Maps/MapUpdater.cpp:57
#12 0x0000000000e0fe99 in DelayExecutor::svc (this=<optimized out>) at /home/azerothcore/src/common/Threading/DelayExecutor.cpp:53
#13 0x00007ffff74cdf6d in ACE_Task_Base::svc_run(void*) () from /usr/lib/libACE-6.3.3.so
#14 0x00007ffff74cee86 in ACE_Thread_Adapter::invoke_i() () from /usr/lib/libACE-6.3.3.so
#15 0x00007ffff74ceda9 in ACE_Thread_Adapter::invoke() () from /usr/lib/libACE-6.3.3.so
#16 0x00007ffff629a4a4 in start_thread (arg=0x7fffb3f35700) at pthread_create.c:456
#17 0x00007ffff553bd0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

7a4af9efece2f5807c295f0f10d5f5dd8cc0012a

##### OPERATING SYSTEM:

Debian 9

##### MODULES:

No

##### OTHER CUSTOMIZATIONS:

No

**Comment by zqgmzq** [comment]
```
2019-07-03 09:21:41 DealDamageAlive
2019-07-03 09:21:41 DealDamageEnd returned 67 damage
2019-07-03 09:21:41 AttackerStateUpdate: (NPC)    130022 attacked 3110822 (TypeId: 3) for 67 dmg, absorbed 0, blocked 0, resisted 0.
2019-07-03 09:21:41 AttackerStateUpdate: (NPC)    129648 attacked 3110822 (TypeId: 3) for 0 dmg, absorbed 0, blocked 0, resisted 0.
2019-07-03 09:21:41 WORLD: Sent SMSG_ATTACKSTART
2019-07-03 09:21:41 Creature (Entry: 28906 GUID: 3110822) chase to creature (GUID: 130022)
2019-07-03 09:21:41 RollMeleeOutcomeAgainst: NORMAL
2019-07-03 09:21:41 DealDamageStart
2019-07-03 09:21:41 deal dmg:70 to health:2026 
2019-07-03 09:21:41 DealDamageAlive
2019-07-03 09:21:41 DealDamageEnd returned 70 damage
2019-07-03 09:21:41 AttackerStateUpdate: (NPC)    3110822 attacked 130022 (TypeId: 3) for 70 dmg, absorbed 0, blocked 0, resisted 0.
2019-07-03 09:21:41 RollMeleeOutcomeAgainst: NORMAL
2019-07-03 09:21:41 DealDamageStart
2019-07-03 09:21:41 deal dmg:53 to health:4566 
2019-07-03 09:21:41 DealDamageAlive
2019-07-03 09:21:41 DealDamageEnd returned 53 damage
2019-07-03 09:21:41 AttackerStateUpdate: (NPC)    130029 attacked 3110822 (TypeId: 3) for 53 dmg, absorbed 0, blocked 0, resisted 0.
2019-07-03 09:21:41 RollMeleeOutcomeAgainst: NORMAL
2019-07-03 09:21:41 DealDamageStart
2019-07-03 09:21:41 deal dmg:12 to health:630 
2019-07-03 09:21:41 DealDamageAlive
2019-07-03 09:21:41 DealDamageEnd returned 12 damage
2019-07-03 09:21:41 AttackerStateUpdate: (NPC)    47446 attacked 2561 (TypeId: 4) for 12 dmg, absorbed 0, blocked 0, resisted 0.
2019-07-03 09:21:41 RollMeleeOutcomeAgainst: NORMAL
2019-07-03 09:21:41 DealDamageStart
2019-07-03 09:21:41 deal dmg:57 to health:4513 
2019-07-03 09:21:41 DealDamageAlive
2019-07-03 09:21:41 DealDamageEnd returned 57 damage
2019-07-03 09:21:41 AttackerStateUpdate: (NPC)    129646 attacked 3110822 (TypeId: 3) for 57 dmg, absorbed 0, blocked 0, resisted 0.
```

```
2019-07-03 09:38:54 Creature 3111226 stopped attacking creature 3111258
2019-07-03 09:38:54 Creature (Entry: 37016 GUID: 3111226) chase to creature (GUID: 201051)
2019-07-03 09:38:54 WORLD: Sent SMSG_ATTACKSTART
2019-07-03 09:38:54 WORLD: Sent SMSG_ATTACKSTOP
2019-07-03 09:38:54 Creature 3111241 stopped attacking creature 3111246
2019-07-03 09:38:54 Creature (Entry: 37027 GUID: 3111241) chase to creature (GUID: 201168)
2019-07-03 09:38:54 DealDamageStart
2019-07-03 09:38:54 deal dmg:59 to health:2502 
2019-07-03 09:38:54 DealDamageAlive
2019-07-03 09:38:54 DealDamageEnd returned 59 damage
2019-07-03 09:38:54 Got WMOAreaTableEntry! flag 0, areaid 0
2019-07-03 09:38:54 WORLD: Sent SMSG_ATTACKSTART
2019-07-03 09:38:54 WORLD: Sent SMSG_ATTACKSTOP
2019-07-03 09:38:54 Creature 3111226 stopped attacking creature 3111258
2019-07-03 09:38:54 Creature (Entry: 37016 GUID: 3111226) chase to creature (GUID: 201051)
2019-07-03 09:38:54 PeriodicTick: 3111247 (TypeId: 3) attacked 3111246 (TypeId: 3) for 16 dmg inflicted by 69911 abs is 0
2019-07-03 09:38:54 DealDamageStart
2019-07-03 09:38:54 deal dmg:16 to health:2443 
2019-07-03 09:38:54 DealDamageAlive
2019-07-03 09:38:54 DealDamageEnd returned 16 damage
2019-07-03 09:38:54 WORLD: Sent SMSG_ATTACKSTART
2019-07-03 09:38:54 WORLD: Sent SMSG_ATTACKSTOP
2019-07-03 09:38:54 Creature 3111241 stopped attacking creature 3111246
2019-07-03 09:38:54 Creature (Entry: 37027 GUID: 3111241) chase to creature (GUID: 201168)
2019-07-03 09:38:54 AttackerStateUpdate: (NPC)    129721 attacked 130354 (TypeId: 3) for 0 dmg, absorbed 0, blocked 0, resisted 0.
2019-07-03 09:38:54 DealDamageStart
2019-07-03 09:38:54 deal dmg:654 to health:4050 
2019-07-03 09:38:54 DealDamageAlive
2019-07-03 09:38:54 DealDamageEnd returned 654 damage
2019-07-03 09:38:54 PeriodicTick: 103579 (TypeId: 3) heal of 103579 (TypeId: 3) for 7185 health inflicted by 1908
```

**Comment by DARKENE** [comment]
update your core!

**Comment by zqgmzq** [comment]
> update your core!
for one commit realy?)
ok, i update it but still have this issue

**Comment by Shard-MW** [comment]
Do you have any custom script ? 
Do you know how the "hacker" procceded to make your core crash ?

**Comment by zqgmzq** [comment]
I assume that this is some kind of software because the server crashes without players entering 
certain packets are being sent to the server port

**Comment by DARKENE** [comment]
Update your core to last, this version not supported!

I want see your report of memory leak...

Someone does not believe me, Maybe they trust you!

**Comment by zqgmzq** [comment]
what do u mean last?
its last revision of core

**Comment by zqgmzq** [comment]
full gdb log
https://pastebin.com/f7erSPWc

**Comment by poszer** [comment]
Duplicate issue https://github.com/azerothcore/azerothcore-wotlk/issues/1895, closing this

**Comment by blackdev01** [comment]
i had this crash today for 20 times .
is there any fix for this issue ?

**Comment by wowmane** [comment]
@zqgmzq 
@blackdev01 
and more fake your id accounts..

I researched about him:

He destroys other servers and So they attack his server, He's a saboteur.

**Comment by FrancescoBorzi** [comment]
This issue is duplicated of:

https://github.com/azerothcore/azerothcore-wotlk/issues/1895

there is no point of commenting it here, so please use the other thread.
