### ISSUE TITLE
Can not success installed with docker installer

### ISSUE THREAD

**Issue by betayi** [azerothcore/azerothcore-wotlk#6511]
**CURRENT BEHAVIOUR:**

I got a new installed clear ubuntu os VM to install the latest azerothcore, and followed the install guild step by step;
but  at step 2:
./acore.sh docker build

log breaked here, with log like this:
Building ac-build       ... done

ERROR: for ac-worldserver  (<Service: ac-worldserver>, 'Build failed')

ERROR: for ac-authserver  (<Service: ac-authserver>, 'Build failed')
ERROR: Service 'ac-authserver' failed to build : Build failed
error: Uncaught (in promise) Error: Failed with error: 1, however,
            it's not related to this Deno script directly. An error occurred within
            the script called by the command itself
          throw new Error(`Failed with error: ${status.code}, however,
                ^
    at Command.<anonymous> (file:///home/beta/azerothcore-wotlk/apps/docker/docker-cmd.ts:290:17)
    at async Promise.all (index 0)
    at async file:///home/beta/azerothcore-wotlk/apps/docker/docker-cmd.ts:240:5

What this problem means ? and what should i do to resolve this ?
and this is a fresh new clear installation.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. 
2. 
3. 

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 

**OPERATING SYSTEM:**

Ubuntu 21.04

**MODULES:**

**CUSTOMIZATIONS:**

**Comment by betayi** [comment]
some dependenc not updated or installed cause of low speed download of github

**Comment by betayi** [comment]
some dependenc not updated or installed cause of low speed download of ubuntu
