### ISSUE TITLE
Worldserver no longer exits correctly

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#7087]
### System details

We use the AC Dashboard setup in production:

https://www.azerothcore.org/wiki/ac-dashboard-core-installation

including the part about tmux (see "Run AzerothCore inside Tmux sessions" and below parts).

We also use the GDB debugger:

https://www.azerothcore.org/wiki/how-to-restart-and-debug

(see the "Advanced restarter (only for bash)" part).

### Problem

Recently we noticed our `worldserver` isn't restarting correctly. Whenever we restart the server using a simple `.server restart xxxx`, it hangs here:

![image](https://user-images.githubusercontent.com/75517/126850373-88507c55-3b21-4db1-b7c3-43d5903728f8.png)

and it takes a manual intervention to kill the process (with ctrl+c):

![image](https://user-images.githubusercontent.com/75517/126850395-5bbc86f7-e993-4448-9a54-fa3e11bbe86f.png)

This should not happen. Whatever is causing this, it has been introduced recently.

### AC Version

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Kitzunu** [comment]
Does it give a crash log before/after ctrl+c?

**Comment by FrancescoBorzi** [comment]
> Does it give a crash log before/after ctrl+c?

this is the most recent `gdb.txt`

```
Thread 1 "worldserver" received signal SIGINT, Interrupt.
futex_wait (private=<optimized out>, expected=12, futex_word=0x7f91a2a661f4) at ../sysdeps/nptl/futex-internal.h:141
10844172.836386 141	../sysdeps/nptl/futex-internal.h: No such file or directory.
#0  futex_wait (private=<optimized out>, expected=12, futex_word=0x7f91a2a661f4) at ../sysdeps/nptl/futex-internal.h:141
#1  futex_wait_simple (private=<optimized out>, expected=12, futex_word=0x7f91a2a661f4) at ../sysdeps/nptl/futex-internal.h:172
#2  __pthread_cond_destroy (cond=0x7f91a2a661d0) at pthread_cond_destroy.c:54
#3  0x0000000001256ca4 in Eluna::~Eluna (this=0x7f91a2a65f00) at /root/env/chromiecraft/azerothcore-wotlk/modules/mod-eluna-lua-engine/LuaEngine/LuaEngine.cpp:204
#4  0x00000000012544b2 in Eluna::Uninitialize () at /root/env/chromiecraft/azerothcore-wotlk/modules/mod-eluna-lua-engine/LuaEngine/LuaEngine.cpp:97
#5  0x0000000000430c1d in main::$_7::operator() (this=<optimized out>) at /root/env/chromiecraft/azerothcore-wotlk/src/server/worldserver/Main.cpp:300
#6  std::_Sp_counted_deleter<decltype(nullptr), main::$_7, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() (this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/shared_ptr_base.h:471
#7  0x000000000042b164 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x7f91551706e0) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/shared_ptr_base.h:155
#8  std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/shared_ptr_base.h:730
#9  std::__shared_ptr<void, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/shared_ptr_base.h:1169
#10 main (argc=<optimized out>, argv=<optimized out>) at /root/env/chromiecraft/azerothcore-wotlk/src/server/worldserver/Main.cpp:409
10844197.204116 [Thread debugging using libthread_db enabled]
10844197.204127 Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
10844197.417814 [New Thread 0x7f7cfbdff700 (LWP 4569)]
10844197.417965 [New Thread 0x7f7cfb5fe700 (LWP 4570)]
10844197.424760 [New Thread 0x7f7cfadfd700 (LWP 4571)]
10844197.427717 [New Thread 0x7f7cfa5fc700 (LWP 4572)]
10844197.429855 [New Thread 0x7f7cf9dfb700 (LWP 4573)]
10844197.436737 [New Thread 0x7f7cf95fa700 (LWP 4574)]
10844197.442265 [New Thread 0x7f7cf8df9700 (LWP 4575)]
10844197.444297 [New Thread 0x7f7cf85f8700 (LWP 4577)]
10844197.621874 [New Thread 0x7f7cf6bff700 (LWP 4581)]
10844206.142819 [New Thread 0x7f7cacdff700 (LWP 4643)]
10844206.143073 [New Thread 0x7f7cabfff700 (LWP 4644)]
10844206.143262 [New Thread 0x7f7cab7fe700 (LWP 4645)]
10844206.143417 [New Thread 0x7f7caaffd700 (LWP 4646)]
10844206.143587 [New Thread 0x7f7caa7fc700 (LWP 4647)]
10844206.143684 [New Thread 0x7f7ca9ffb700 (LWP 4648)]
10844206.143802 [New Thread 0x7f7ca97fa700 (LWP 4649)]
10844206.143936 [New Thread 0x7f7ca8ff9700 (LWP 4650)]
10844206.476707 [New Thread 0x7f7ca21ff700 (LWP 4651)]
10844206.476943 [New Thread 0x7f7ca19fe700 (LWP 4652)]
10844206.722839 [New Thread 0x7f7ca0bff700 (LWP 4653)]
10844206.722936 [New Thread 0x7f7ca03fe700 (LWP 4654)]
11338976.326754 [Thread 0x7f7ca03fe700 (LWP 4654) exited]
11338976.337022 [Thread 0x7f7cfb5fe700 (LWP 4570) exited]
11338976.337061 [Thread 0x7f7cfbdff700 (LWP 4569) exited]
11338976.454136 [Thread 0x7f7ca0bff700 (LWP 4653) exited]
11338976.619997 [Thread 0x7f7ca19fe700 (LWP 4652) exited]
11338977.584170 [Thread 0x7f7ca21ff700 (LWP 4651) exited]
11338979.679721 [Thread 0x7f7cab7fe700 (LWP 4645) exited]
11338979.680926 [Thread 0x7f7ca8ff9700 (LWP 4650) exited]
11338979.681708 [Thread 0x7f7ca97fa700 (LWP 4649) exited]
11338979.682000 [Thread 0x7f7caa7fc700 (LWP 4647) exited]
11338979.683466 [Thread 0x7f7ca9ffb700 (LWP 4648) exited]
11338979.687583 [Thread 0x7f7cacdff700 (LWP 4643) exited]
11338979.689068 [Thread 0x7f7cabfff700 (LWP 4644) exited]
11338979.689773 [Thread 0x7f7caaffd700 (LWP 4646) exited]

Thread 1 "worldserver" received signal SIGINT, Interrupt.
futex_wait (private=<optimized out>, expected=12, futex_word=0x7f7cfc2661f4) at ../sysdeps/nptl/futex-internal.h:141
11339163.403724 141	../sysdeps/nptl/futex-internal.h: No such file or directory.
#0  futex_wait (private=<optimized out>, expected=12, futex_word=0x7f7cfc2661f4) at ../sysdeps/nptl/futex-internal.h:141
#1  futex_wait_simple (private=<optimized out>, expected=12, futex_word=0x7f7cfc2661f4) at ../sysdeps/nptl/futex-internal.h:172
#2  __pthread_cond_destroy (cond=0x7f7cfc2661d0) at pthread_cond_destroy.c:54
#3  0x0000000001256ca4 in Eluna::~Eluna (this=0x7f7cfc265f00) at /root/env/chromiecraft/azerothcore-wotlk/modules/mod-eluna-lua-engine/LuaEngine/LuaEngine.cpp:204
#4  0x00007f7cb3d03be0 in ?? ()
#5  0x00007f7cbe2cd378 in ?? ()
#6  0x00007f7cb3d03be0 in ?? ()
#7  0x00007f7cfc22b7a0 in ?? ()
#8  0x00007f7cfc265f00 in ?? ()
#9  0x0000000000000002 in ?? ()
#10 0x00007f7cfc2a2700 in ?? ()
#11 0x00000000012544b2 in Eluna::Uninitialize () at /root/env/chromiecraft/azerothcore-wotlk/modules/mod-eluna-lua-engine/LuaEngine/LuaEngine.cpp:97
#12 0x00007f7cbe2cd378 in ?? ()
#13 0x0000000000f81428 in MapUpdater::deactivate (this=<optimized out>) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Maps/MapUpdater.cpp:86
#14 0x00007f7cbe2cd301 in ?? ()
#15 0x0000000000000000 in ?? ()
11339188.597648 [Thread debugging using libthread_db enabled]
11339188.597659 Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
11339188.836879 [New Thread 0x7f3ad7dff700 (LWP 6489)]
11339188.837017 [New Thread 0x7f3ad75fe700 (LWP 6490)]
11339188.844868 [New Thread 0x7f3ad6dfd700 (LWP 6491)]
11339188.847523 [New Thread 0x7f3ad65fc700 (LWP 6492)]
11339188.849389 [New Thread 0x7f3ad5dfb700 (LWP 6493)]
11339188.856339 [New Thread 0x7f3ad55fa700 (LWP 6494)]
11339188.862126 [New Thread 0x7f3ad4df9700 (LWP 6495)]
11339188.863957 [New Thread 0x7f3ad45f8700 (LWP 6497)]
[Detaching after fork from child process 6501]
[Detaching after fork from child process 6503]
[Detaching after fork from child process 6504]
[Detaching after fork from child process 6505]
[Detaching after fork from child process 6506]
[Detaching after fork from child process 6507]
[Detaching after fork from child process 6508]
[Detaching after fork from child process 6509]
[Detaching after fork from child process 6510]
[Detaching after fork from child process 6511]
[Detaching after fork from child process 6512]
[Detaching after fork from child process 6513]
[Detaching after fork from child process 6514]
[Detaching after fork from child process 6515]
[Detaching after fork from child process 6516]
[Detaching after fork from child process 6517]
[Detaching after fork from child process 6518]
[Detaching after fork from child process 6519]
[Detaching after fork from child process 6520]
[Detaching after fork from child process 6521]
[Detaching after fork from child process 6522]
[Detaching after fork from child process 6523]
[Detaching after fork from child process 6524]
[Detaching after fork from child process 6525]
[Detaching after fork from child process 6526]
[Detaching after fork from child process 6527]
[Detaching after fork from child process 6528]
[Detaching after fork from child process 6529]
[Detaching after fork from child process 6530]
[Detaching after fork from child process 6531]
11339205.603237 [New Thread 0x7f3a897ff700 (LWP 6585)]
11339205.603435 [New Thread 0x7f3a889ff700 (LWP 6586)]
11339205.603566 [New Thread 0x7f3a881fe700 (LWP 6587)]
11339205.603717 [New Thread 0x7f3a879fd700 (LWP 6588)]
11339205.604108 [New Thread 0x7f3a871fc700 (LWP 6589)]
11339205.604233 [New Thread 0x7f3a869fb700 (LWP 6590)]
11339205.604333 [New Thread 0x7f3a861fa700 (LWP 6591)]
11339205.604499 [New Thread 0x7f3a859f9700 (LWP 6592)]
11339206.507963 [New Thread 0x7f3a7ebff700 (LWP 6594)]
11339206.508158 [New Thread 0x7f3a7e3fe700 (LWP 6595)]
11339206.841502 [New Thread 0x7f3a7cdff700 (LWP 6596)]
11339206.842412 [New Thread 0x7f3a7c5fe700 (LWP 6597)]
```

**Comment by locus313** [comment]
@FrancescoBorzi maybe this shutdown issue could be addressed by this pr:
https://github.com/azerothcore/azerothcore-wotlk/pull/5425
