### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#9060]
```

Thread 3 "worldserver" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x14c7833fe700 (LWP 20404)]
0x000000000155a2fe in Acore::Abort (file=0x16325b7 "/root/env/chromiecraft/azerothcore-wotlk/src/server/worldserver/Main.cpp", line=646, function=0x1891455 "Handler") at /root/env/chromiecraft/azerothcore-wotlk/src/common/Debugging/Errors.cpp:115
115	        Crash(formattedMessage.c_str());
#0  0x000000000155a2fe in Acore::Abort (file=0x16325b7 "/root/env/chromiecraft/azerothcore-wotlk/src/server/worldserver/Main.cpp", line=646, function=0x1891455 "Handler") at /root/env/chromiecraft/azerothcore-wotlk/src/common/Debugging/Errors.cpp:115
#1  0x0000000000435861 in FreezeDetector::Handler (freezeDetectorRef=..., error=...) at /root/env/chromiecraft/azerothcore-wotlk/src/server/worldserver/Main.cpp:646
#2  0x00000000004500f9 in std::__invoke_impl<void, void (*&)(std::weak_ptr<FreezeDetector>, boost::system::error_code const&), std::weak_ptr<FreezeDetector>&, boost::system::error_code const&> (__f=<optimized out>, __args=..., __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:60
#3  std::__invoke<void (*&)(std::weak_ptr<FreezeDetector>, boost::system::error_code const&), std::weak_ptr<FreezeDetector>&, boost::system::error_code const&> (__fn=<optimized out>, __args=..., __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:95
#4  std::_Bind<void (*(std::weak_ptr<FreezeDetector>, std::_Placeholder<1>))(std::weak_ptr<FreezeDetector>, boost::system::error_code const&)>::__call<void, boost::system::error_code const&, 0ul, 1ul>(std::tuple<boost::system::error_code const&>&&, std::_Index_tuple<0ul, 1ul>) (this=0x14c7833fc410, __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/functional:400
#5  std::_Bind<void (*(std::weak_ptr<FreezeDetector>, std::_Placeholder<1>))(std::weak_ptr<FreezeDetector>, boost::system::error_code const&)>::operator()<boost::system::error_code const&, void>(boost::system::error_code const&) (this=0x14c7833fc410, __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/functional:482
#6  boost::asio::detail::binder1<std::_Bind<void (*(std::weak_ptr<FreezeDetector>, std::_Placeholder<1>))(std::weak_ptr<FreezeDetector>, boost::system::error_code const&)>, boost::system::error_code>::operator()() (this=0x14c7833fc410) at /usr/include/boost/asio/detail/bind_handler.hpp:65
#7  boost::asio::asio_handler_invoke<boost::asio::detail::binder1<std::_Bind<void (*(std::weak_ptr<FreezeDetector>, std::_Placeholder<1>))(std::weak_ptr<FreezeDetector>, boost::system::error_code const&)>, boost::system::error_code> >(boost::asio::detail::binder1<std::_Bind<void (*(std::weak_ptr<FreezeDetector>, std::_Placeholder<1>))(std::weak_ptr<FreezeDetector>, boost::system::error_code const&)>, boost::system::error_code>&, ...) (function=...) at /usr/include/boost/asio/handler_invoke_hook.hpp:69
#8  boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder1<std::_Bind<void (*(std::weak_ptr<FreezeDetector>, std::_Placeholder<1>))(std::weak_ptr<FreezeDetector>, boost::system::error_code const&)>, boost::system::error_code>, std::_Bind<void (*(std::weak_ptr<FreezeDetector>, std::_Placeholder<1>))(std::weak_ptr<FreezeDetector>, boost::system::error_code const&)> >(boost::asio::detail::binder1<std::_Bind<void (*(std::weak_ptr<FreezeDetector>, std::_Placeholder<1>))(std::weak_ptr<FreezeDetector>, boost::system::error_code const&)>, boost::system::error_code>&, std::_Bind<void (*(std::weak_ptr<FreezeDetector>, std::_Placeholder<1>))(std::weak_ptr<FreezeDetector>, boost::system::error_code const&)>&) (function=..., context=...) at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#9  boost::asio::detail::asio_handler_invoke<boost::asio::detail::binder1<std::_Bind<void (*(std::weak_ptr<FreezeDetector>, std::_Placeholder<1>))(std::weak_ptr<FreezeDetector>, boost::system::error_code const&)>, boost::system::error_code>, std::_Bind<void (*(std::weak_ptr<FreezeDetector>, std::_Placeholder<1>))(std::weak_ptr<FreezeDetector>, boost::system::error_code const&)>, boost::system::error_code>(boost::asio::detail::binder1<std::_Bind<void (*(std::weak_ptr<FreezeDetector>, std::_Placeholder<1>))(std::weak_ptr<FreezeDetector>, boost::system::error_code const&)>, boost::system::error_code>&, boost::asio::detail::binder1<std::_Bind<void (*(std::weak_ptr<FreezeDetector>, std::_Placeholder<1>))(std::weak_ptr<FreezeDetector>, boost::system::error_code const&)>, boost::system::error_code>*) (function=..., this_handler=0x14c7833fc410) at /usr/include/boost/asio/detail/bind_handler.hpp:106
#10 boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder1<std::_Bind<void (*(std::weak_ptr<FreezeDetector>, std::_Placeholder<1>))(std::weak_ptr<FreezeDetector>, boost::system::error_code const&)>, boost::system::error_code>, boost::asio::detail::binder1<std::_Bind<void (*(std::weak_ptr<FreezeDetector>, std::_Placeholder<1>))(std::weak_ptr<FreezeDetector>, boost::system::error_code const&)>, boost::system::error_code> >(boost::asio::detail::binder1<std::_Bind<void (*(std::weak_ptr<FreezeDetector>, std::_Placeholder<1>))(std::weak_ptr<FreezeDetector>, boost::system::error_code const&)>, boost::system::error_code>&, boost::asio::detail::binder1<std::_Bind<void (*(std::weak_ptr<FreezeDetector>, std::_Placeholder<1>))(std::weak_ptr<FreezeDetector>, boost::system::error_code const&)>, boost::system::error_code>&) (function=..., context=...) at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#11 boost::asio::detail::io_object_executor<boost::asio::io_context::executor_type>::dispatch<boost::asio::detail::binder1<std::_Bind<void (*(std::weak_ptr<FreezeDetector>, std::_Placeholder<1>))(std::weak_ptr<FreezeDetector>, boost::system::error_code const&)>, boost::system::error_code>, std::allocator<void> >(boost::asio::detail::binder1<std::_Bind<void (*(std::weak_ptr<FreezeDetector>, std::_Placeholder<1>))(std::weak_ptr<FreezeDetector>, boost::system::error_code const&)>, boost::system::error_code>&&, std::allocator<void> const&) const (this=<optimized out>, f=..., a=...) at /usr/include/boost/asio/detail/io_object_executor.hpp:119
#12 boost::asio::detail::handler_work<std::_Bind<void (*(std::weak_ptr<FreezeDetector>, std::_Placeholder<1>))(std::weak_ptr<FreezeDetector>, boost::system::error_code const&)>, boost::asio::detail::io_object_executor<boost::asio::io_context::executor_type>, boost::asio::detail::io_object_executor<boost::asio::io_context::executor_type> >::complete<boost::asio::detail::binder1<std::_Bind<void (*(std::weak_ptr<FreezeDetector>, std::_Placeholder<1>))(std::weak_ptr<FreezeDetector>, boost::system::error_code const&)>, boost::system::error_code> >(boost::asio::detail::binder1<std::_Bind<void (*(std::weak_ptr<FreezeDetector>, std::_Placeholder<1>))(std::weak_ptr<FreezeDetector>, boost::system::error_code const&)>, boost::system::error_code>&, std::_Bind<void (*(std::weak_ptr<FreezeDetector>, std::_Placeholder<1>))(std::weak_ptr<FreezeDetector>, boost::system::error_code const&)>&) (this=<optimized out>, function=..., handler=...) at /usr/include/boost/asio/detail/handler_work.hpp:72
#13 boost::asio::detail::wait_handler<std::_Bind<void (*(std::weak_ptr<FreezeDetector>, std::_Placeholder<1>))(std::weak_ptr<FreezeDetector>, boost::system::error_code const&)>, boost::asio::detail::io_object_executor<boost::asio::io_context::executor_type> >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) (owner=0x14c783a7e100, base=<optimized out>) at /usr/include/boost/asio/detail/wait_handler.hpp:73
#14 0x000000000043ca27 in boost::asio::detail::scheduler_operation::complete (this=0x14c567f81a60, owner=0x14c783a7e100, ec=..., bytes_transferred=22830303576176) at /usr/include/boost/asio/detail/scheduler_operation.hpp:40
#15 boost::asio::detail::scheduler::do_run_one (this=0x14c783a7e100, lock=..., this_thread=..., ec=...) at /usr/include/boost/asio/detail/impl/scheduler.ipp:447
#16 0x000000000043c551 in boost::asio::detail::scheduler::run (this=0x14c783a7e100, ec=...) at /usr/include/boost/asio/detail/impl/scheduler.ipp:200
#17 0x0000000000455a18 in boost::asio::io_context::run (this=<optimized out>) at /usr/include/boost/asio/impl/io_context.ipp:63
#18 Acore::Asio::IoContext::run (this=<optimized out>) at /root/env/chromiecraft/azerothcore-wotlk/src/common/Asio/IoContext.h:45
#19 0x000014c7863e0de4 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#20 0x000014c7864fb609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#21 0x000014c7860d0293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
3129135.124827 [Thread debugging using libthread_db enabled]
3129135.124835 Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Thread 33 "worldserver" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x145da63ff700 (LWP 32174)]
0x0000000001559e47 in Acore::Assert (file=0x1892428 "/root/env/chromiecraft/azerothcore-wotlk/src/server/shared/Network/SocketMgr.h", line=35, function=0x1892477 "~SocketMgr", debugInfo=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
, message=0x1892482 "!_threads && !_acceptor && !_threadCount", format=<optimized out>) at /root/env/chromiecraft/azerothcore-wotlk/src/common/Debugging/Errors.cpp:78
78	        Crash(formattedMessage.c_str());
#0  0x0000000001559e47 in Acore::Assert (file=0x1892428 "/root/env/chromiecraft/azerothcore-wotlk/src/server/shared/Network/SocketMgr.h", line=35, function=0x1892477 "~SocketMgr", debugInfo=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
, message=0x1892482 "!_threads && !_acceptor && !_threadCount", format=<optimized out>) at /root/env/chromiecraft/azerothcore-wotlk/src/common/Debugging/Errors.cpp:78
#1  0x000000000114de83 in SocketMgr<WorldSocket>::~SocketMgr (this=<optimized out>) at /root/env/chromiecraft/azerothcore-wotlk/src/server/shared/Network/SocketMgr.h:35
#2  0x0000146109a1ba27 in __run_exit_handlers (status=-1, listp=0x146109bbd718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#3  0x0000146109a1bbe0 in __GI_exit (status=<optimized out>) at exit.c:139
#4  0x000000000045e22b in ACSoapThread (host=..., port=<optimized out>) at /root/env/chromiecraft/azerothcore-wotlk/src/server/worldserver/ACSoap/ACSoap.cpp:40
#5  0x0000146109e04de4 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x0000146109f1f609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x0000146109af4293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

### AC Version

https://github.com/chromiecraft/azerothcore-wotlk/commit/27b880876dd411b2433ec227d69f6f79dc0c3ce4

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Kitzunu** [comment]
Please dont dump a crashlog in the issue. Use Gist or PasteBin

**Comment by FrancescoBorzi** [comment]
> Please dont dump a crashlog in the issue. Use Gist or PasteBin

I've shortened it :)

**Comment by Kitzunu** [comment]
```cpp
            else if (getMSTimeDiff(freezeDetector->_lastChangeMsTime, curtime) > freezeDetector->_maxCoreStuckTimeInMs)
            {
                LOG_ERROR("server.worldserver", "World Thread hangs, kicking out server!");
                ABORT();
            }
```

**Comment by Kitzunu** [comment]
cc @Winfidonarleyan

**Comment by Mitradis** [comment]
this is a single crash?

**Comment by Voidx** [comment]
Some more info please

**Comment by UltraNix** [comment]
Close it as no info included in that crashlog. New crashlogs should have all needed info to track the problem.
